{
    "E-mail и ID" : "isAllowedLoginByEmailAndId",
    "По телефону по умолчанию" : "isDefaultLoginByPhone",
    "По телефону":"isAllowedLoginByPhone",
    "Ввод кода страны вручную":"isAllowedCustomPhoneCodeInput",
    "Через соц. сети":"isAllowedLoginBySocial",
    "Восстановление пароля без активации телефона":"isAllowedChangePasswordWithoutPhone",
    "Восстановление пароля разрешенные страны при геоблоке":"RestorePasswordAllowedCountries",
    "Восстановление пароля запрещенные страны":"RestorePasswordForbiddenCountries",
    "Авторизация по QR":"isAllowedLoginByQr",
    "Доп. инфо в активации телефона":"hasAdditionalInfoForPhoneActivation",
    "Ввод кода страны вручную":"isAllowedCustomPhoneCodeInput",
    "Чекбокс Минимальный возраст (значение в чекбоксе)":"minimumAge",
    "Правила (ссылка на сайт)":"linkToRules",
    "Политика конфиденциальности (ссылка на сайт)":"linkToPrivacy",
    "Использование приложения без авторизации":"hasAllowedAppWithoutAuth",
    "Требовать активацию телефона после авторизации":"hasAllowedAppOnlyWithActivatePhone",
    "Требовать верификацию после авторизации":"hasBlockAuthUprid",
    "Алерт на популярном":"hasAlertPopular",
    "Баланс":"hasPopularBalance",
    "Поиск":"hasPopularSearch",
    "Фильтрация спортов":"popularSportsCount",
    "Лента Games":"hasPopularGamesCarusel",
    "Баннеры":"hasBanners",
    "Табы":"popularTab",
    "Настроить (Настройка популярного)":"hasMainscreenSettings",
    "Сообщения":"hasDirectMessages",
    "host для платег":"paymentHost",
    "Экспресс дня":"hasAccumulatorOfTheDay",
    "Генерация купона":"hasCouponGenerator",
    "Загрузить купон / Сохранить купон":"hasUploadCoupon",
    "Ставка по промокоду":"hasPromocodes",
    "Точный коэффициент":"hasOrdersBets",
    "VIP-ставка (только для Линии)":"hasVipBet",
    "Аванс":"hasAdvancedBets",
    "Спойлер с налогами по умолчанию":"hasTaxSpoilerDefault",
    "Одиночная":"hasSingleBet",
    "Экспресс":"hasAccumulatorBet",
    "Система":"hasSystemBet",
    "Лаки":"hasLuckyBet",
    "Цепочка":"hasChainBet",
    "Патент":"hasPatentBet",
    "Мультиставка":"hasMultiBet",
    "Условная ставка":"hasConditionalBet",
    "Антиэкспресс":"hasAntiAccumulatorBet",
    "Одиночные (Мультиодинар)":"hasMultiSingleBet",
    "История тото":"hasSectionToto",
    "История заявок":"hasOrdersBets",
    "История казино":"hasHistoryCasino",
    "Нерассчитанные ставки":"hasHistoryUncalculated",
    "Скрыть историю":"hasHistoryHide",
    "Период":"bettingHistoryPeriod",
    "Выбор периода":"hasHistoryPeriodFilter",
    "Печать купона":"hasCouponPrint",
    "Сохранение купона картинкой":"hasSharingCouponPicture",
    "Запросить историю на e-mail":"hasHistoryToEmail",
    "Редактирование купона":"hasBetEdit",
    "Автопродажа":"hasBetAutoSell",
    "Страховка":"hasBetInsure",
    "Полная продажа":"hasBetSellFull",
    "Частичная продажа":"hasBetSellPart",
    "Powerbet":"hasPowerBet",
    "Округлять значение при продаже (костыль казахов)":"hasBetSellRoundValue",
    "Скрытие ставок":"hasHideBets",
    "Киберспорт":"hasCyberSport",
    "Virtual":"hasSectionVirtual",
    "1xGames":"hasSectionXGames",
    "Поддержка":"hasSectionSupport",
    "Аутентификатор":"hasAuthenticator",
    "Live/Линия Киберы":"hasCyberVirtualTab",
    "Экспресс дня":"hasAccumulatorOfTheDay",
    "1xZone (Экран игры)":"hasZone",
    "Стрим (Трансляции)":"hasStream",
    "Спорт - Киберспорт - Наличие раздела (+реальные)":"hasCyberSport",
    "Спорт - Таб Виртуальный (Киберы - Марбл, киберзона)":"hasCyberVirtualTab",
    "Спорт - Таб 1xCyber (Киберстрим)":"hasCyberCyberStreamTab",
    "Спорт - SportGamesTV":"hasSportGamesTV",
    "Спорт - Результаты":"hasResults",
    "Спорт - Ставки на своих":"hasNationalTeamBet",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",


}
